### ISSUE TITLE
Dupe glitch

### ISSUE THREAD

**Issue by wvbigdave** [zizmax/AcuteLoot#3] opened 2020-08-03 01:43 UTC
I don't know where to post this, but my users have found that if they open, loot, and close rapidly on chests that are naturally spawned, it duplicates the gear over and over. Only gear that dupes is any gear modded by the plugin.

**Comment by zizmax** [comment] 2020-08-03 04:31
Hmm, that's not good and I'll definitely look into it. 
1) What plugin version and Minecraft version are you running?
2) does it only happen if you do it really quickly, or always?
3) does it duplicate the exact same items again, or it just creates more and more different items?

**Comment by wvbigdave** [comment] 2020-08-03 05:52
Ok, yeah, sorry about posting there and here.  Found the link after I posted there.  Anyway, I am using AcuteLoot 1.0.2 and Paper 1.16.1 build 128. It happened with another user, I will see if he can reproduce while recording it for you. He described it as being done very rapidly and it was different drops I believe. I have messaged him but he is asleep right now. Since he knows the exact steps to reproduce it.  Also, I can get you anything you need.  Just let me know! I am always happy to help.

**Comment by zizmax** [comment] 2020-08-03 14:37
Thanks for your willingness to help out with this! I'm trying to wrap my head around what could be happening here. You wouldn't happen to have any gamerules or plugins that affect chest loot would you?

**Comment by wvbigdave** [comment] 2020-08-03 19:14
No other plugins for that no. And as for gamerule, only modified rule is to stop firetick. Everything else is default.

**Comment by DrippTripp** [comment] 2020-08-03 21:31
Hi, I am the user that found out the bug, It was whenever i opened a chest the was in a village or Temple, it would randomly spawn items anywhere from seeds to Netherite Armour and tools, It has slowed down but that could just Wvbigdave changing something. I don't have a recording of the happening but I am not sure what is going on.

**Comment by zizmax** [comment] 2020-08-05 19:05
Thank you both for more information. I'm still looking into it.

- Did it happen specifically in villages and temples, and no where else like dungeons or sunken ships?

- Was it specifically when you closed/open the chest really fast (like spam clicking)? Or any type of clicking, regardless of speed?

**Comment by DrippTripp** [comment] 2020-08-05 23:15
It would happen in villages and temples, I am not sure about sunken ships because I have not tried it. and when I spammed open and close is when you usually happened, I have not done it for a day or two, but If i hop on today and get it on record for you to see.

**Comment by zizmax** [comment] 2020-08-06 03:27
That might prove very helpful. Thank you!

**Comment by zizmax** [comment] 2020-08-06 03:43
I've tried opening chests in multiple villages now, opening and closing as quickly as I can and I'm still unable to reproduce the bug... I'm really not sure what be going on and I'm really curious to see your clip!

**Comment by DrippTripp** [comment] 2020-08-06 18:39
When I’m back at my computer in 1 hour I’ll record and try to get the dupe glitch

**Comment by zizmax** [comment] 2020-08-10 23:24
> When I’m back at my computer in 1 hour I’ll record and try to get the dupe glitch

Any more word on this? I have an idea for what it could maybe be, but I'm still unable to reproduce it myself which makes it impossible to test adequately. It would be very helpful to see it in action.

**Comment by wvbigdave** [comment] 2020-08-25 06:51
I am soooo sorry this didn't get replied to.  I also have an idea because I have ran into a couple of other plugins that had and issue and I tracked it down to Drop2Inventory. But I would love to hear what you have.

**Comment by zizmax** [comment] 2020-11-02 01:18
I am closing this issue due to non-response. I have done extensive testing and have never been able to recreate the issue. If the issue occurs again, please provide detailed steps to recreate it. A video demonstration would be very helpful as well.

**Closed by zizmax** 2020-11-02 01:18 UTC
