### ISSUE TITLE
Death is now Turned to stone permitly

### ISSUE THREAD

**Issue by Spiritotter** [zizmax/AcuteLoot#11] opened 2020-12-17 21:49 UTC
after getting shot with gorgan bow we have just Turned to stone as death mesage no matter how we die how can I fix this

**Comment by zizmax** [comment] 2020-12-17 21:59
Hi @Spiritotter, thanks for reporting this issue! I think I know the cause and will look into it in the next couple hours!

**Comment by zizmax** [comment] 2020-12-18 00:13
@Spiritotter I just pushed v2.0.4 which contains a fix for this issue. Please let me know if you find any more bugs!

**Comment by Spiritotter** [comment] 2020-12-18 00:40
Thanks so much! I will be on the look out. I love finding bugs it's a bit of a weird hobby.

**Closed** 2020-12-18 00:40 UTC
